[package]
name = "sortuniq"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

edition = "2018"

[dependencies]

[dependencies.clap]
version = "2"
default-features = false

[profile.release]
lto = true
panic = "abort"
