[package]
name = "muchutils"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
clap = "2"
lru = "0.6"

[dev-dependencies]
tempfile = "3"

[profile.release]
lto = true
